project_name: pigHosts

before:
  hooks:
    - task mod-vendor
builds:
  id: "pigHosts"
  main: ./cmd/pighosts/main.go
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
archives:
- replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
