project_name: pigHosts
before:
  hooks:
    - task mod-vendor
builds:
  id: "pigHosts"
  main: ./cmd/pighosts/main.go
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
  id: "pigHosts"
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: zip
  replacements:
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - README.md
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
