project_name: pigHosts
dist: ../dist
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
before:
  hooks:
    - task mod-vendor
builds:
  -
    id: "pigHosts"
    main: ./cmd/pighosts/main.go
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
archives:
  -
    id: "pigHosts"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
  algorithm: md5
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: goldfix
    name: pigHosts

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: false

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "{{.ProjectName}}-v{{.Version}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false
