# https://taskfile.dev

version: '2'

vars:
  VER: 1
  TOOL: pigHosts

env:
  GO111MODULE: on

tasks:
  default:
    cmds:
      - echo "{{.VER}} {{.TOOL}}"
  build-mod-vendor:
    desc: Download modules and force a build of project using vendor folder.
    deps: [mod-vendor]
    cmds:
      - go build -mod vendor -i -a -o $GOPATH/bin/pigHosts.exe ./cmd/...
  build:
    desc: Build project using vendor folder.
    cmds:
      - go build -mod vendor -i -o $GOPATH/bin/pigHosts.exe ./cmd/...
  mod-vendor:
    desc: Download module into vendor folder.
    cmds:
      - go mod vendor
  go-env:
    desc: View GO environment
    cmds:
      - go env
  go-test:
    desc: Run all tests.
    cmds:
      - go clean -testcache
      - go test ./...

